// This file is autogenerated from src/shared/constants.yaml
// DO NOT EDIT DIRECTLY! Edit above YAML file and run 'npm run build:constants'.

export const coefficients = {
    "EV_TO_RY": 0.0734986444,
    "BOHR_TO_ANGSTROM": 0.529177210544,
    "ANGSTROM_TO_BOHR": 1.8897261259077822,
    "EV_A_TO_RY_BOHR": 0.0388938075966032
};

export const tolerance = {
    "length": 0.01,
    "lengthAngstrom": 0.001,
    "pointsDistance": 0.001
};

export const units = {
    "bohr": "bohr",
    "angstrom": "angstrom",
    "degree": "degree",
    "radian": "radian",
    "alat": "alat"
};

export const ATOMIC_COORD_UNITS = {
    "crystal": "crystal",
    "cartesian": "cartesian"
};

export const HASH_TOLERANCE = 3;

export default {
    coefficients,
    tolerance,
    units,
    ATOMIC_COORD_UNITS,
    HASH_TOLERANCE,
};
