const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

// Define paths relative to the project root
const yamlPath = path.join(process.cwd(), 'src/shared/constants.yaml');
const jsPath = path.join(process.cwd(), 'src/js/shared/constants.js');
const pyPath = path.join(process.cwd(), 'src/py/mat3ra/utils/constants.py');

try {
    // Read and parse the YAML file
    const rawData = fs.readFileSync(yamlPath, 'utf-8');
    const constants = yaml.load(rawData);

    // Build  JS content
    let jsContent = `// This file is autogenerated from src/shared/constants.yaml\n` +
                    `// DO NOT EDIT DIRECTLY! Edit above YAML file and run ` +
                    `'npm run build:constants'.\n\n`;

    // Dynamically generate individual exports for every top-level key
    const keys = Object.keys(constants);
    for (const key of keys) {
        jsContent += `export const ${key} = ${JSON.stringify(constants[key], null, 4)};\n\n`;
    }

    // Dynamically generate the default export block
    jsContent += `export default {\n`;
    for (const key of keys) {
        jsContent += `    ${key},\n`;
    }
    jsContent += `};\n`;

    fs.mkdirSync(path.dirname(jsPath), { recursive: true });
    fs.writeFileSync(jsPath, jsContent, 'utf-8');

    console.log(`✅ Successfully generated JS constants at: ${jsPath}`);

    // Build Python content
    let pyContent = `# This file is autogenerated from src/shared/constants.yaml\n` +
                    `# DO NOT EDIT DIRECTLY! Edit above YAML file and run` +
                    `'npm run build:constants'.\n`;

    for (const key of Object.keys(constants)) {
        // In Python, standard practice is to use UPPERCASE for constants
        const pyKey = key.toUpperCase();

        // Stringify the object, but replace JS native types with Python native types
        let pyValue = JSON.stringify(constants[key], null, 4)
            .replace(/: true/g, ': True')
            .replace(/: false/g, ': False')
            .replace(/: null/g, ': None');

        pyContent += `\n${pyKey} = ${pyValue}\n`;
    }

    fs.mkdirSync(path.dirname(pyPath), { recursive: true });
    fs.writeFileSync(pyPath, pyContent, 'utf-8');
    console.log(`✅ Successfully generated Python constants at: ${pyPath}`);
} catch (error) {
    console.error("❌ Failed to build constants.js:", error.message);
    process.exit(1);
}
